---
- name: Provision Demo Environment
  hosts: all
  become: true
  vars:
    towerpass: password1
    ldaplicense: False

  roles:
    - vagrant-common
    - { role: openldap, when: "'tag_Name_ldapvm' in group_names and 'ldaplicense' == True" }
    - { role: tower, when: "'tag_Name_Tower' in group_names" }
