---
# tasks file for common
- name: install network tools
  yum: name=net-tools state=present

- name: place authorized keys file
  authorized_key:  
    user: vagrant
    state: present
    key: '{{ item }}'
  with_items:
    - https://raw.githubusercontent.com/hashicorp/vagrant/master/keys/vagrant.pub
    # - https://github.com/dfederlein.keys  # Place your keys' URL or file location here

- include_tasks: "vagrant_ext.yml"
  when: "'tag_Vagrant_ext' in group_names"
